version: '3'

services:
  app1:
    image: thunderboltfrontend:v2aug19
    ports:
      - "3001:3001"  # For accessing the application directly if needed

  app2:
    image: thunderboltfrontend:v2aug19  # You can use the same image for a second instance
    ports:
      - "3002:3001"  # Map to a different host port

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - app1
      - app2

