version: '3'

services:
  app1:
    image: thunderboltfrontend:v2aug19
    ports:
      - "3001:3001"  # Optional, for debugging

  app2:
    image: thunderboltfrontend:v2aug19  # Same image for another instance
    ports:
      - "3002:3001"  # Map to a different host port for direct access if needed

  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"  # Expose Caddy on port 80
    depends_on:
      - app1
      - app2

